---
title: "Understanding Your Data"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Background

The CDU Data Science team and Applied Information team initiated a workshop meeting with those interested in "understanding your data" in the first week of March 2021. This was started in response to our need to ensure that the solutions we create are understood by everyone and that we are concentrating on the right problems.

This will be a continuous two-way discussion facilitated by the CDU Data Science Team and will also include analysts from Applied Information and Performance. 

The Understanding Your Data also links into the initiative of Data Clinics where particular specific support has been given to teams with their data. This has been facilitated by our Clinical Analyst.

# Meeting dates

To try to accommodate as many diaries as possible the day of the meeting will change each month and always be at the same time (11-12pm):

## 2021

Monday 26 July [Blog post](https://cdu-data-science-team.github.io/understanding-your-data/posts/2021-07-28-collecting-data-and-reporting-through-mhsds/)  
Tuesday 24 August [Blog post](https://cdu-data-science-team.github.io/understanding-your-data/posts/2021-08-24-dashboards-and-reports/)  
Wednesday 29 September [Slides from the meeting](https://cdu-data-science-team.github.io/presentations/2021-09-29%20UYD%20spreadsheet%20accessibility/UYD-Spreadsheet-Accessibility.html#1)  
Thursday 28 October
Friday 26 November

## 2022

Monday 21 January
Tuesday 22 February
Monday 28 March - Presentations from ICS projects  
Thursday 28 April – Inequalities in Front End   
Friday 27 May – Inequalities in Back End Data  
Monday 27 June – Adding Wider Data to Enhance (ICS)  

If you would like to know more about these meetings and come along (meetings are on MS Teams), please contact [CDU Data Science Team](mailto:cdudatascience@nottshc.nhs.uk).

For Nottinghamshire Healthcare NHS Foundation Trust staff on the Trust network: The team's calendar is open to view by selecting Folder/Select Calendar and searching for CDU Data Science. 
