---
title: "April 2021 Meeting"
description: |
  CDU Data Science Roadmap and a summary of the topics discussed in this month's meeting.
author:
  - name: Zoë Turner
    url: https://twitter.com/Letxuga007
date: 04-07-2021
output:
  distill::distill_article:
    toc: true
    self_contained: false
categories:
  - Training
  - Public Health
  - CDU Data Science Team
  - Maps
  - Data Clinics
  - Patient Feedback
preview: img/willow-catkin.png       
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# CDU Data Science Roadmap

The video of the presentation by Chris Beeley is viewable in on the Trust's Microsoft Stream site: https://web.microsoftstream.com/video/41df2da8-eac3-4391-8e0c-a4ef0a853688?list=studio (will require an authorised log in).

https://cdu-data-science-team.github.io/presentations/2021-03-01%20CDU%20Data%20Science%20Team%20Roadmap/roadmap.html#1

<iframe src="https://cdu-data-science-team.github.io/presentations/2021-03-01%20CDU%20Data%20Science%20Team%20Roadmap/roadmap.html#1" width="600" height="400" loading="lazy" allowfullscreen></iframe> <script>fitvids('.shareagain', {players: 'iframe'});</script>

More information on the team and what we do was presented by Milan Wiedemann. Slides are [here](https://docs.google.com/presentation/d/10su0anky4s7rQ7ivpwN1cZvIrgJRSfJP5NB4L5y7aW8/edit#slide=id.gcc47524736_1_112).

# Themes from the events

## Training

Training was something we hadn't considered but came up as a theme. Analysts main software tools are Excel, PowerBI, SQL and R. 

### R and R Studio

Nottinghamshire Healthcare NHS Foundation Trust allows all staff to access R and R Studio for download through the Software Centre (accessible through the Windows Start button). 

Training is offered through [NHS-R Community](https://nhsrcommunity.com/events/) every month. The course is led by Zoë Turner. Course materials are available [here](https://philosopher-analyst.netlify.app/collection/).

Shiny training is being offered through [NHS-R Community](https://nhsrcommunity.com/events/) and is being designed and led by Chris Beeley. Course materials are available [here](https://github.com/ChrisBeeley/shinyworkshop) and specifically for [beginners](https://github.com/ChrisBeeley/shiny_beginners).

Help for R can be sought from the Slack channel nhsrcommunity.slack.com. Also note that there is a Government Data Science Slack channel govdatascience.slack.com but access to this is restricted to certain email addresses like nhs.net and not individual Trust accounts.

## Mapping

Another general interest that came from the group was mapping data and tools used for this are often QGIS. This is also available through the Software Centre but specific access may be required through IT.

### Public Health Mapping tools

There are a couple of Public Health mapping tools that are available and more information can be found [here](https://cdu-data-science-team.github.io/miscellany/Mapping.html).

## Data clinics

Some individual pieces of work have come out of the Understanding your data meeting and have moved into the data clinic initiative discussed more [here](https://cdu-data-science-team.github.io/team-blog/posts/2021-01-13-data-clinics-in-nottinghamshire-healthcare/)

## Patient Feedback

Nottinghamshire Healthcare NHS Foundation Trust's Patient Feedback (including [Care Opinion](https://www.careopinion.org.uk/services/rha) information) can be found [here](http://suce.co.uk:8080/apps/SUCE/).

