---
title: "Initial Meeting"
description: |
  Communications which were used to promote the purpose of the meetings.
author:
  - name: Zoë Turner
    url: https://twitter.com/Letxuga007
date: 02-03-2021
output:
  distill::distill_article:
    toc: true
    self_contained: false
categories:
  - Communications   
preview: img/leaves.png  
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Initial communication

The following is the initial communication shared through John Brewin, Chief Executive of Nottinghamshire Healthcare's NHS Foundation Trust, daily emails. 

* Are you interested in understanding your data better?
* Do you have questions about what is going on in your service you feel like you currently can't answer?
* Do you have ideas for ways of presenting and understanding data that you don't have the time to make a reality?
* Would you be interested in looking at data, analyses, and dashboards and feeding back your opinions about them?

Applied Information and the Clinical Development Unit work together to collate, process, and analyse all sorts of datasets for national reporting as well as internal analysis, audit, evaluation, and research. We are trying to make sense of the data in the Trust but we need to hear from people out in services who can tell us what they want and don't want, and can look at analytic products that we make and give us feedback on them.

If you're interested in being a part of the way that the Trust develops its tools for analysing data there are lots of ways you can be involved- coming to a workshop, testing tools in your own time and feeding back your opinions, coming with your own ideas about tools or analyses you would like to see or just commenting on our plans and helping to shape the future of what we produce.

# Staff Notices

The following has been posted on the Staff Notices on the Nottinghamshire Healthcare's NHS Foundation Trust's Intranet:

>The next Understanding Your Data meeting for those interested in “understanding your data” will be Friday 4 June from 11.30am to 12.30pm. This was started in response to our need to ensure that the solutions we create are understood by everyone and that we are concentrating on the right problems.

>This will be a continuous two-way discussion facilitated by the CDU Data Science Team and will also include analysts from Applied Information and Performance and everyone is welcome, please contact zoe.turner2@nottshc.nhs.uk to join this virtual meeting and/or for more information. Also see our website with information https://cdu-data-science-team.github.io/team-blog/uyd.html

